import type { Project, User } from "@/types/project"

// Update some users to have empty avatar strings to demonstrate our custom avatar
export const initialProjects: Project[] = [
  {
    id: "1",
    title: "Website Redesign",
    description: "Redesign the company website with new branding",
    createdBy: {
      id: "user1",
      name: "Alex Johnson",
      email: "alex@example.com",
      avatar: "",
      role: "full_access",
    },
    members: [
      {
        id: "user1",
        name: "Alex Johnson",
        email: "alex@example.com",
        avatar: "",
        role: "full_access",
      },
      {
        id: "user2",
        name: "Maria Garcia",
        email: "maria@example.com",
        avatar: "", // Empty avatar to use our custom component
        role: "read_only",
      },
      {
        id: "user3",
        name: "Sam Lee",
        email: "sam@example.com",
        avatar: "",
        role: "complete_only",
      },
    ],
    tasks: [
      {
        id: "task1",
        title: "Design homepage mockup",
        description: "Create a mockup for the new homepage design",
        completed: true,
        createdAt: "2023-10-15T10:30:00Z",
        dueDate: "2023-10-20T18:00:00Z",
        priority: "high",
        category: "design",
        completion: {
          completedBy: "user1",
          completedAt: "2023-10-18T14:30:00Z",
        },
      },
      {
        id: "task2",
        title: "Implement responsive layout",
        description: "Make sure the website works on all devices",
        completed: false,
        createdAt: "2023-10-16T09:15:00Z",
        dueDate: "2023-10-25T18:00:00Z",
        priority: "medium",
        category: "development",
      },
      {
        id: "task3",
        title: "Add content management system",
        description: "Integrate a CMS for easy content updates",
        completed: false,
        createdAt: "2023-10-17T14:45:00Z",
        dueDate: "2023-11-05T18:00:00Z",
        priority: "low",
        category: "development",
      },
    ],
    createdAt: "2023-10-10T08:00:00Z",
  },
  {
    id: "2",
    title: "Mobile App Development",
    description: "Create a mobile app for our customers",
    createdBy: {
      id: "user1",
      name: "Alex Johnson",
      email: "alex@example.com",
      avatar: "",
      role: "full_access",
    },
    members: [
      {
        id: "user1",
        name: "Alex Johnson",
        email: "alex@example.com",
        avatar: "",
        role: "full_access",
      },
      {
        id: "user4",
        name: "John Smith",
        email: "john@example.com",
        avatar: "", // Empty avatar to use our custom component
        role: "read_only",
      },
    ],
    tasks: [
      {
        id: "task4",
        title: "Create wireframes",
        description: "Design wireframes for all app screens",
        completed: true,
        createdAt: "2023-11-05T11:30:00Z",
        dueDate: "2023-11-10T18:00:00Z",
        priority: "high",
        category: "design",
        completion: {
          completedBy: "user1",
          completedAt: "2023-11-09T16:45:00Z",
        },
      },
      {
        id: "task5",
        title: "Develop UI components",
        description: "Build reusable UI components for the app",
        completed: true,
        createdAt: "2023-11-11T09:45:00Z",
        dueDate: "2023-11-20T18:00:00Z",
        priority: "medium",
        category: "development",
        completion: {
          completedBy: "user1",
          completedAt: "2023-11-18T11:30:00Z",
        },
      },
      {
        id: "task6",
        title: "Implement authentication",
        description: "Add user login and registration functionality",
        completed: false,
        createdAt: "2023-11-21T14:15:00Z",
        dueDate: "2023-12-01T18:00:00Z",
        priority: "high",
        category: "development",
      },
      {
        id: "task7",
        title: "Test on different devices",
        description: "Ensure app works on various device sizes and OS versions",
        completed: false,
        createdAt: "2023-11-25T10:00:00Z",
        dueDate: "2023-12-10T18:00:00Z",
        priority: "medium",
        category: "testing",
      },
    ],
    createdAt: "2023-11-01T09:30:00Z",
  },
  {
    id: "3",
    title: "Marketing Campaign",
    description: "Q1 Product Launch Marketing Campaign",
    createdBy: {
      id: "user5",
      name: "Emily Chen",
      email: "emily@example.com",
      avatar: "",
      role: "full_access",
    },
    members: [
      {
        id: "user5",
        name: "Emily Chen",
        email: "emily@example.com",
        avatar: "",
        role: "full_access",
      },
      {
        id: "user1",
        name: "Alex Johnson",
        email: "alex@example.com",
        avatar: "",
        role: "complete_only",
      },
      {
        id: "user3",
        name: "Sam Lee",
        email: "sam@example.com",
        avatar: "",
        role: "read_only",
      },
    ],
    tasks: [
      {
        id: "task8",
        title: "Create social media content calendar",
        description: "Plan posts for Twitter, Instagram, and LinkedIn",
        completed: true,
        createdAt: "2023-12-01T09:00:00Z",
        dueDate: "2023-12-10T18:00:00Z",
        priority: "high",
        category: "marketing",
        completion: {
          completedBy: "user5",
          completedAt: "2023-12-08T16:30:00Z",
        },
      },
      {
        id: "task9",
        title: "Design promotional materials",
        description: "Create banners, flyers and digital assets",
        completed: false,
        createdAt: "2023-12-05T11:15:00Z",
        dueDate: "2023-12-20T18:00:00Z",
        priority: "medium",
        category: "design",
      },
      {
        id: "task10",
        title: "Prepare press release",
        description: "Write and distribute press release to media outlets",
        completed: false,
        createdAt: "2023-12-08T14:30:00Z",
        dueDate: "2023-12-25T18:00:00Z",
        priority: "high",
        category: "marketing",
      },
    ],
    createdAt: "2023-12-01T08:00:00Z",
  },
  {
    id: "4",
    title: "Product Analytics Dashboard",
    description: "Build a real-time analytics dashboard for our product",
    createdBy: {
      id: "user1",
      name: "Alex Johnson",
      email: "alex@example.com",
      avatar: "",
      role: "full_access",
    },
    members: [
      {
        id: "user1",
        name: "Alex Johnson",
        email: "alex@example.com",
        avatar: "",
        role: "full_access",
      },
      {
        id: "user2",
        name: "Maria Garcia",
        email: "maria@example.com",
        avatar: "", // Empty avatar to use our custom component
        role: "full_access",
      },
      {
        id: "user4",
        name: "John Smith",
        email: "john@example.com",
        avatar: "", // Empty avatar to use our custom component
        role: "read_only",
      },
    ],
    tasks: [
      {
        id: "task11",
        title: "Define key metrics",
        description: "Identify the most important metrics to track",
        completed: true,
        createdAt: "2023-11-15T10:00:00Z",
        dueDate: "2023-11-20T18:00:00Z",
        priority: "high",
        category: "planning",
        completion: {
          completedBy: "user1",
          completedAt: "2023-11-19T15:45:00Z",
        },
      },
      {
        id: "task12",
        title: "Design dashboard layout",
        description: "Create wireframes and mockups for the dashboard",
        completed: true,
        createdAt: "2023-11-21T09:30:00Z",
        dueDate: "2023-11-30T18:00:00Z",
        priority: "medium",
        category: "design",
        completion: {
          completedBy: "user2",
          completedAt: "2023-11-28T14:20:00Z",
        },
      },
      {
        id: "task13",
        title: "Implement data visualization",
        description: "Create charts and graphs for the dashboard",
        completed: false,
        createdAt: "2023-12-01T11:00:00Z",
        dueDate: "2023-12-15T18:00:00Z",
        priority: "high",
        category: "development",
      },
      {
        id: "task14",
        title: "Connect to data sources",
        description: "Integrate with our analytics API",
        completed: false,
        createdAt: "2023-12-05T13:45:00Z",
        dueDate: "2023-12-20T18:00:00Z",
        priority: "high",
        category: "development",
      },
    ],
    createdAt: "2023-11-10T08:30:00Z",
  },
  {
    id: "5",
    title: "Customer Support Portal",
    description: "Develop a new customer support portal with ticketing system",
    createdBy: {
      id: "user4",
      name: "John Smith",
      email: "john@example.com",
      avatar: "", // Empty avatar to use our custom component
      role: "full_access",
    },
    members: [
      {
        id: "user4",
        name: "John Smith",
        email: "john@example.com",
        avatar: "", // Empty avatar to use our custom component
        role: "full_access",
      },
      {
        id: "user1",
        name: "Alex Johnson",
        email: "alex@example.com",
        avatar: "",
        role: "read_only",
      },
      {
        id: "user3",
        name: "Sam Lee",
        email: "sam@example.com",
        avatar: "",
        role: "complete_only",
      },
    ],
    tasks: [
      {
        id: "task15",
        title: "Research ticketing systems",
        description: "Compare different ticketing system solutions",
        completed: true,
        createdAt: "2023-10-20T09:15:00Z",
        dueDate: "2023-10-30T18:00:00Z",
        priority: "medium",
        category: "research",
        completion: {
          completedBy: "user4",
          completedAt: "2023-10-28T11:30:00Z",
        },
      },
      {
        id: "task16",
        title: "Design user interface",
        description: "Create mockups for the support portal",
        completed: true,
        createdAt: "2023-11-01T10:00:00Z",
        dueDate: "2023-11-15T18:00:00Z",
        priority: "high",
        category: "design",
        completion: {
          completedBy: "user3",
          completedAt: "2023-11-12T16:45:00Z",
        },
      },
      {
        id: "task17",
        title: "Implement authentication",
        description: "Add user login and registration",
        completed: false,
        createdAt: "2023-11-16T13:30:00Z",
        dueDate: "2023-11-30T18:00:00Z",
        priority: "high",
        category: "development",
      },
      {
        id: "task18",
        title: "Create ticket management system",
        description: "Develop the core ticketing functionality",
        completed: false,
        createdAt: "2023-12-01T09:45:00Z",
        dueDate: "2023-12-20T18:00:00Z",
        priority: "high",
        category: "development",
      },
    ],
    createdAt: "2023-10-15T08:00:00Z",
  },
]

// Update some available users to have empty avatar strings

// Keep the current user as is
export const currentUser: User = {
  id: "user1",
  name: "Alex Johnson",
  email: "alex@example.com",
  avatar: "",
  role: "full_access",
};

export const availableUsers: User[] = [
  {
    id: "user1",
    name: "Alex Johnson",
    email: "alex@example.com",
    avatar: "",
    role: "full_access",
  },
  {
    id: "user2",
    name: "Maria Garcia",
    email: "maria@example.com",
    avatar: "",
    role: "read_only",
  },
  {
    id: "user3",
    name: "Sam Lee",
    email: "sam@example.com",
    avatar: "",
    role: "read_only",
  },
  {
    id: "user4",
    name: "John Smith",
    email: "john@example.com",
    avatar: "",
    role: "read_only",
  },
  {
    id: "user5",
    name: "Emily Chen",
    email: "emily@example.com",
    avatar: "",
    role: "read_only",
  },
];